[workspace]
resolver = "2"
members = ["crates/chummer-core", "crates/chummer-gui", "crates/chummer-cli"]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/shamblashini/chummer-rs"

[workspace.dependencies]
chummer-core = { path = "crates/chummer-core" }
quick-xml = "0.42"
thiserror = "2"
anyhow = "1"
lzma-rust2 = { version = "0.21", default-features = false, features = ["std", "encoder"] }

[profile.release]
lto = "thin"
codegen-units = 1
