#!/usr/bin/env python3
"""Generate crates/chummer-core/src/bonus/generic.rs from Chummer5a's
AddImprovementCollection.cs: every handler whose body is a single
CreateImprovement built from plain fields becomes one table row.

usage: tools/gen_bonus_table.py /path/to/chummer5a > crates/chummer-core/src/bonus/generic.rs
"""
import re, sys

src = open(sys.argv[1] + "/Chummer/Backend/Improvements/AddImprovementCollection.cs").read()
meths = list(re.finditer(r'public void (\w+)\(XmlNode bonusNode\)\s*\{', src))

def split_args(s):
    out, depth, cur = [], 0, ''
    for ch in s:
        if ch in '([': depth += 1
        if ch in ')]': depth -= 1
        if ch == ',' and depth == 0:
            out.append(cur.strip()); cur = ''
        else:
            cur += ch
    out.append(cur.strip())
    return out

def name_expr(a):
    if a == 'string.Empty': return 'N::Empty'
    m = re.fullmatch(r'bonusNode\["(\w+)"\]\?\.InnerTextViaPool\(\)( \?\? string\.Empty)?', a)
    if m: return f'N::Child("{m.group(1)}")'
    if a == 'bonusNode.InnerTextViaPool()': return 'N::Text'
    m = re.fullmatch(r'"([^"]*)"', a)
    if m: return f'N::Lit("{m.group(1)}")'
    return None

def num_expr(a):
    if a in ('0', '0m'): return 'V::Zero'
    if re.fullmatch(r'ImprovementManager\.ValueTo(?:Dec|Int)\(_objCharacter, bonusNode\.InnerTextViaPool\(\), _intRating\)', a): return 'V::Text'
    m = re.fullmatch(r'ImprovementManager\.ValueTo(?:Dec|Int)\(_objCharacter, bonusNode\["(\w+)"\]\?\.InnerTextViaPool\(\), _intRating\)', a)
    if m: return f'V::Child("{m.group(1)}")'
    if re.fullmatch(r'-?\d+', a): return f'V::Lit({a})'
    return None

def uniq(a):
    if a == '_strUnique': return 'U::Bonus'
    m = re.fullmatch(r'"([^"]*)"', a)
    return f'U::Lit("{m.group(1)}")' if m else None

def cond(a):
    if a in ('string.Empty', '""'): return 'None'
    m = re.fullmatch(r'bonusNode\["(\w+)"\]\?\.InnerTextViaPool\(\) \?\? string\.Empty', a)
    return f'Some("{m.group(1)}")' if m else None

rows = []
for i, m in enumerate(meths):
    name = m.group(1)
    end = meths[i + 1].start() if i + 1 < len(meths) else len(src)
    body = src[m.end():end]
    body = re.sub(r'if \(bonusNode == null\)\s*throw new ArgumentNullException\(nameof\(bonusNode\)\);', '', body)
    body = re.sub(r'//[^\n]*', '', body).strip()
    body = body[:body.rfind('}')].strip()
    mm = re.fullmatch(r'CreateImprovement\((.*)\);', body, re.S)
    if not mm: continue
    args = split_args(re.sub(r'\s+', ' ', mm.group(1)))
    if len(args) < 5 or args[1] != '_objImprovementSource' or args[2] != 'SourceName': continue
    t = re.fullmatch(r'Improvement\.ImprovementType\.(\w+)', args[3])
    if not t: continue
    # CreateImprovement defaults: value 0, rating 1, the rest 0/empty.
    defaults = ['0', '1', '0', '0', '0', '0', 'string.Empty', 'false', 'string.Empty', 'string.Empty']
    extra = args[5:] + defaults[len(args[5:]):] + ['0']
    n, u = name_expr(args[0]), uniq(args[4])
    val, rating, mn, mx, aug, am = num_expr(extra[0]), extra[1], num_expr(extra[2]), num_expr(extra[3]), num_expr(extra[4]), num_expr(extra[5])
    exc, atr, tgt = extra[6], extra[7], extra[8]
    cnd = cond(extra[9]) if len(args) > 14 else 'None'
    if None in (n, u, val, mn, mx, aug, am, cnd): continue
    if rating not in ('1', '0') or exc not in ('string.Empty', '0', '""') or atr not in ('false', '0') or tgt not in ('string.Empty', '0', '""'):
        continue
    rows.append(f'    G {{ node: "{name}", kind: "{t.group(1)}", name: {n}, unique: {u}, val: {val}, rating: {rating}, min: {mn}, max: {mx}, aug: {aug}, aug_max: {am}, condition: {cnd} }},')

print('//! Generated by tools/gen_bonus_table.py from Chummer5a\'s')
print('//! AddImprovementCollection.cs. Do not edit by hand.')
print('//!')
print('//! Each row is a handler that creates exactly one improvement from plain')
print('//! fields of the bonus node.')
print()
print('use super::handlers::{G, N, U, V};')
print()
print('#[rustfmt::skip]')
print('pub const GENERIC: &[G] = &[')
print('\n'.join(rows))
print('];')
